services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  metastore-db:
    image: postgres:16
    container_name: metastore-db
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: metastore
      POSTGRES_PASSWORD: metastore
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    ports:
      - "5432:5432"
    volumes:
      - metastore-db:/var/lib/postgresql/data

  hive-metastore:
    image: starburstdata/hive-metastore:336.0.1
    container_name: hive-metastore
    depends_on:
      - minio
      - metastore-db
    environment:
      HIVE_METASTORE_PORT: 9083
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore-db:5432/metastore
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_USER: metastore
      HIVE_METASTORE_PASSWORD: metastore
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "minio"
      S3_SECRET_KEY: "minio123"
      S3_PATH_STYLE_ACCESS: "true"
      REGION: us-east-1
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_WASB_ACCESS_KEY: ""
      METASTORE_WAREHOUSE_DIR: "s3a://datalake/"
    ports:
      - "9083:9083"

  trino:
    image: trinodb/trino:479
    container_name: trino
    depends_on:
      - hive-metastore
      - minio
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino

volumes:
  minio-data:
  metastore-db:
